packages:
  # Include all of the core configuration
  core: !include trmnl.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: jesserockz.trmnl
    version: dev # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://jesserockz/esphome-trmnl/trmnl.yaml@main

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:

button:
  - platform: factory_reset
    name: Factory Reset
    id: factory_reset_button

binary_sensor:
  - id: !extend back_button
    on_multi_click:
      - timing:
          - ON for at least 3s
          - OFF for at least 0.5s
        then:
          - button.press: factory_reset_button
